[server]
maxUploadSize = 5000
enableCORS = false
enableXsrfProtection = false
headless = true

[browser]
gatherUsageStats = false

[runner]
fastReruns = false
enforceSerializableSessionState = false

[client]
toolbarMode = "minimal"
